site_name: My Docs
docs_dir: './docs'

theme:
  name: material
  palette:
    - scheme: slate
  features:
    - navigation.sections 
    - navigation.indexes
    - navigation.footer

exclude_docs: |
  .*
  _*

repo_url: https://github.com/skedastically/mkdocs-macros-gimmicks
repo_name: skedastically/mkdocs-macros-gimmicks

markdown_extensions:
  - admonition
  - pymdownx.details  
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes
  - pymdownx.snippets

plugins:
  - search
  - macros:
      modules: [main,extras]
  - awesome-nav

extra:
  macro_blob_url: https://github.com/skedastically/mkdocs-macros-gimmicks/blob/main/main.py
  macro_raw_url: https://raw.githubusercontent.com/skedastically/mkdocs-macros-gimmicks/refs/heads/main/main.py

hooks:
  - hooks.py