site_name: My Docs
docs_dir: './docs'

theme:
  name: material
  palette:
    - scheme: slate
  features:
    - navigation.sections 
    - navigation.indexes
    - navigation.footer

exclude_docs: |
  .*
  _*

repo_url: https://github.com/skedastically/mkdocs-macro-gimmicks
repo_name: skedastically/mkdocs-macro-gimmicks

markdown_extensions:
  - admonition
  - pymdownx.details  
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - footnotes

plugins:
  - search
  - macros
  - awesome-nav

extra:
  patch_blob_url: https://github.com/skedastically/mkdocs-macro-gimmicks/blob/main/awesome-nav-tweak.patch
  patch_url: https://raw.githubusercontent.com/skedastically/mkdocs-macro-gimmicks/refs/heads/main/awesome-nav-tweak.patch